/*
TOPICS TO BE COVERED
=> Intro to Nodejs, Brief discussion on V8 engine.
=> Hello world in Nodejs - writing and executing the code using VsCode terminal
=> Exporting functionaliities in Nodejs using module.exports and exports
=> Importing functionalities in Nodejs using require
=> Intro to NPM
=> Installing modules locally and globally using NPM
=> Uninstalling modules using npm
=> Initialising an NPM project, brief discussion on package.json
=> What are core modules of Node?
=> Introduction to FS core module of Node

==> Introduction to Node JS
=> A javaScript Runtime environment
=> Built on chrome's v8 engine!
=> light, scalable and open-source language platform
=> Used for server-side development
    -> Node js is formed by v8 engine, and it is run time environment
        for javascript.
    ->Also -- JAVA is a compilled language and it is compilled by using JRE.
            JRE - JAVE RUNTIME ENVIRONMENT
            AND it goes to JVM i.e., java virtual machine
    -> But, JavaScript is a INTERPRETED and even base language,
            which compilled at the time of running the application , so that 
            the load of application can be reduced - that means - just in time compilation
            and there is word just in time means - runtime i.e., before running a file just compilling
            IT just started AOT - ADD OF TIME (AOT IS SAME AS COMPILLED TIME) 
*/